version: "3.8"
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8000:8000"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      #- BPL_DEBUG_SUSPEND=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
     # - SPRING_PROFILES_ACTIVE=testdata

  order-service:
    depends_on:
      - polar-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - "9002:9002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #- BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_SUSPEND=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
     # - SPRING_PROFILES_ACTIVE=testdata

  edge-service:
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - "9000:9080"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      #- BPL_DEBUG_SUSPEND=true

  # Backing Services

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  polar-redis:
    image: "redis:7.2.3-alpine"
    container_name: "polar-redis"
    ports:
      - 6379:6379

volumes:
  postgres-data:
